### ISSUE TITLE
2.0.0版本编译报错

### ISSUE THREAD

**Issue by momtboy** [Fliggy-Android-Team/fsuper#10]
`/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart:157:3: Error: Type 'MouseCursor' not found.
  MouseCursor effectiveMouseCursor;
  ^^^^^^^^^^^
/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart:157:3: Error: 'MouseCursor' isn't a type.
  MouseCursor effectiveMouseCursor;
  ^^^^^^^^^^^
/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart:161:60: Error: 'MouseCursor' isn't a type.
    effectiveMouseCursor = MaterialStateProperty.resolveAs<MouseCursor>(
                                                           ^^^^^^^^^^^
/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart:162:7: Error: The getter 'MaterialStateMouseCursor' isn't defined for the class 'FControlState'.
 - 'FControlState' is from 'package:fcontrol/fcontrol.dart' ('/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MaterialStateMouseCursor'.
      MaterialStateMouseCursor.clickable,
      ^^^^^^^^^^^^^^^^^^^^^^^^
/D:/FlutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/fcontrol-1.0.0/lib/fcontrol.dart:248:7: Error: No named parameter with the name 'cursor'.
      cursor: effectiveMouseCursor,
`

**Comment by momtboy** [comment]
官方没人答复一下？？？？？？？

**Comment by chenBingX** [comment]
参考这个 Issues 哦
  [https://github.com/Fliggy-Mobile/fsuper/issues/8](https://github.com/Fliggy-Mobile/fsuper/issues/8)
