### ISSUE TITLE
onClick如何添加点击效果？

### ISSUE THREAD

**Issue by limhGeek** [Fliggy-Android-Team/fsuper#4]
FSuper控件的onClick怎么给他添加点击效果？

**Comment by chenBingX** [comment]
FSuper 目前没有对点击效果的直接支持哦。如果希望配置点击效果，可以考虑使用 [FButton](https://github.com/Fliggy-Android-Team/fbutton) 哦。
OR
可以不通过 `onClick` 属性配置点击事件，而是直接通过使用 **InkWell** 等 **Widget** 包裹。
