### ISSUE TITLE
小红点的 redPointColor 属性设置不生效

### ISSUE THREAD

**Issue by zhou0818** [Fliggy-Android-Team/fsuper#5]
翻了下源码，貌似是固定设置成 Colors.redAccent 了。

**Comment by chenBingX** [comment]
非常感谢您的反馈，在新的版本中这个问题会被修正。欢迎持续关注 **FWidget** 哦😄。

**Comment by itMcdull** [comment]
下一版本什么时候发布呢,这个问题导致目前无法使用该库.

**Comment by chenBingX** [comment]
你好，在最新的 2.0.0 版本中，这个问题已经得到修复。
欢迎继续保持对 **FWidget** 的关注哦😄
