### ISSUE TITLE
child2位于fsuper外侧时，onChild2Click无法生效

### ISSUE THREAD

**Issue by nothinggift** [Fliggy-Android-Team/fsuper#7]
看起来这是stack本身的问题，可以参考这个 https://stackoverflow.com/questions/51366761/in-flutter-how-can-a-positioned-widget-feel-taps-outside-of-its-parent-stack-ar

**Comment by chenBingX** [comment]
感谢反馈，接下来这个问题会被跟进的。

**Comment by chenBingX** [comment]
你好，在最新的 `2.0.0` 版本中，这个问题已经得到修复。
欢迎继续保持对 **FWidget** 的关注哦😄
