### ISSUE TITLE
fcontrol-1.0.0/lib/fcontrol.dart:157:3: Error: Type 'MouseCursor' not found.

### ISSUE THREAD

**Issue by leielyq** [Fliggy-Android-Team/fsuper#8]
fcontrol-1.0.0/lib/fcontrol.dart:157:3: Error: Type 'MouseCursor' not found.

导入就会报错

**Comment by chenBingX** [comment]
flutter 版本升级下

**Comment by leielyq** [comment]
@chenBingX  [√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale zh-CN)

**Comment by chenBingX** [comment]
MouseCursor 是新特性，在 1.19 版本被加入

**Comment by leielyq** [comment]
好的，fsuper可以和tab配合使用吗？貌似颜色不会自动变成选中或不选中的颜色

**Comment by chenBingX** [comment]
需要手动修改颜色

**Comment by leielyq** [comment]
好的
