### ISSUE TITLE
在2.0.0的版本,Undefined name 'FCorner'.

### ISSUE THREAD

**Issue by thisdk** [Fliggy-Android-Team/fsuper#9]
如题.我flutter的版本升级到master的版本,但是FCorner还是不存在.
请问我该怎么办

![image](https://user-images.githubusercontent.com/23514168/87405878-97eef980-c5f2-11ea-926d-d4c5921b4081.png)

**Comment by momtboy** [comment]
我也遇到这个问题咯。。。。

**Comment by chenBingX** [comment]
加上：

```
import 'package:fcontrol/fdefine.dart';
```
